# Generated by Django 5.1.4 on 2024-12-27 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userService', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='dogsService/media/')),
                ('sex', models.CharField(max_length=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userService.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsService.dogstatus')),
            ],
        ),
    ]
