# Generated by Django 5.1.4 on 2024-12-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0004_user_last_login_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
