# Generated by Django 5.1.4 on 2024-12-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0005_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
