# Generated by Django 5.1.4 on 2024-12-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_analysis',
            name='countryName',
        ),
    ]
