# Generated by Django 5.1.4 on 2024-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipService', '0002_remove_ip_analysis_countryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_analysis',
            name='countryCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
