# Generated by Django 5.1.4 on 2024-12-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipService', '0003_alter_ip_analysis_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_analysis',
            name='latitude',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ip_analysis',
            name='longitude',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
